# Generated by Django 6.0.6 on 2026-06-08 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, help_text='URL para onde o botão do banner levará', verbose_name='Link (CTA)')),
                ('link_text', models.CharField(default='Saiba Mais', max_length=80, verbose_name='Texto do Botão')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Banners com menor número aparecem primeiro', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Ex.: bi-tree-fill (Bootstrap Icons)', max_length=60, verbose_name='Ícone Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('text', models.TextField(verbose_name='Depoimento')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Foto do Cliente')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Deixe em branco para 'Consulte-nos'", max_digits=10, null=True, verbose_name='Preço (R$)')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional (R$)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagem Principal')),
                ('unit', models.CharField(default='m²', help_text='Ex.: m², m³, un, dúzia', max_length=30, verbose_name='Unidade de Medida')),
                ('is_featured', models.BooleanField(default=False, help_text='Marque para exibir na seção de destaques/promoções da Home', verbose_name='Produto em Destaque')),
                ('is_promotion', models.BooleanField(default=False, help_text='Exibe badge de PROMOÇÃO no card do produto', verbose_name='Em Promoção')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
