# Generated by Django 6.0.6 on 2026-06-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='📐 TAMANHO RECOMENDADO: 1920 × 580 px (proporção 16:5 — paisagem bem larga). 📏 MÍNIMO ACEITÁVEL: 1280 × 400 px. 🗂️ FORMATOS: JPG ou WebP (PNG aceito, mas gera arquivo maior). ⚠️ ZONA SEGURA DE TEXTO: os textos (Título, Subtítulo e Botão) aparecem na metade ESQUERDA da imagem, com overlay escuro. Evite colocar elementos importantes (rosto, logotipo, produto) nos primeiros 55% da largura a partir da esquerda — eles ficarão cobertos pelo texto. Prefira imagens com o assunto principal centralizado ou no lado DIREITO. Em mobile, o texto é centralizado e cobre maior parte da tela, então garanta contraste em toda a imagem.', upload_to='banners/', verbose_name='Imagem do Banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Texto complementar ao título — máximo 2 linhas. Será exibido abaixo do título, ainda sobre a imagem.', max_length=300, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Será exibido em destaque sobre a imagem. Use textos curtos e diretos (até 8 palavras) para melhor legibilidade.', max_length=200, verbose_name='Título'),
        ),
    ]
