# Generated by Django 6.0.6 on 2026-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banner_image_alter_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Resumo para o Google (recomendado ~150 caracteres).', verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para o Google. Se vazio, usará o nome da categoria.', max_length=150, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Resumo para o Google.', verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para o Google (caso tenha página própria no futuro).', max_length=150, verbose_name='Meta Title (SEO)'),
        ),
    ]
