# Generated by Django 6.0.6 on 2026-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_meta_description_category_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eyebrow', models.CharField(default='NOSSA LOCALIZAÇÃO', max_length=100, verbose_name='Texto de Apoio (Eyebrow)')),
                ('title_main', models.CharField(default='ONDE NOS ENCONTRAR EM PORTO ALEGRE', max_length=150, verbose_name='Título Principal')),
                ('card_title', models.CharField(default='VENHA TOMAR UM CAFÉ COM A GENTE!', max_length=100, verbose_name='Título do Card')),
                ('address_line1', models.CharField(default='Av. Protásio Alves, 2599', max_length=150, verbose_name='Endereço Linha 1')),
                ('address_line2', models.CharField(default='Sala 507 - Petrópolis, Porto Alegre - RS', max_length=150, verbose_name='Endereço Linha 2')),
                ('cep', models.CharField(default='CEP 97140-870', max_length=20, verbose_name='CEP')),
                ('business_hours', models.TextField(default='Seg a Qui: 09h às 19:30h\nSex: 08:30h às 20h\nPlantão Urgência 24h', verbose_name='Horários de Funcionamento')),
                ('map_iframe_url', models.URLField(help_text='Vá no Google Maps > Compartilhar > Incorporar um mapa > Copie apenas o link dentro do src="..."', max_length=500, verbose_name='Link de Incorporação (Iframe) do Mapa')),
                ('route_url', models.URLField(help_text='Link direto do Google Maps para abrir a navegação até o local', max_length=500, verbose_name="Link 'Traçar Rota'")),
                ('whatsapp_number', models.CharField(default='5551999999999', max_length=20, verbose_name='Número do WhatsApp')),
            ],
            options={
                'verbose_name': 'Localização da Empresa',
                'verbose_name_plural': 'Localização da Empresa',
            },
        ),
    ]
