# Generated by Django 6.0.6 on 2026-06-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companylocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyLocation',
        ),
    ]
