# Generated by Django 6.0.6 on 2026-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_companylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Código HEX da cor do texto (ex: #FFFFFF para branco, #000000 para preto, #FF0000 para vermelho).', max_length=7, verbose_name='Cor do Texto'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, help_text='URL para onde o banner levará. Obrigatório se não houver Título.', verbose_name='Link (CTA)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_text',
            field=models.CharField(blank=True, default='Saiba Mais', help_text='Se o título estiver vazio, este botão será ignorado e toda a imagem será clicável.', max_length=80, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text='Opcional. Se não for preenchido, o link do banner será obrigatório, e toda a imagem será clicável.', max_length=200, null=True, verbose_name='Título'),
        ),
    ]
