# Generated by Django 6.0.6 on 2026-06-11 17:42

import uuid
from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            base_slug = slugify(product.name)
            slug = base_slug
            counter = 1
            while Product.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            product.slug = slug
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_slug_productimage'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
