# Generated by Django 6.0.6 on 2026-06-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_product_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Campanha')),
                ('active', models.BooleanField(default=False, help_text='Se marcada, esta campanha substituirá os destaques padrão da página inicial. Apenas a última campanha ativa terá efeito.', verbose_name='Ativa')),
                ('featured_title', models.CharField(default='Produtos em Destaque para Sua Obra', max_length=200, verbose_name='Título da Área de Destaque')),
                ('featured_subtitle', models.TextField(blank=True, default='Seleção especial de materiais de construção com preços exclusivos na Madeireira São Luiz.', verbose_name='Subtítulo da Área de Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Selecione os produtos que farão parte desta campanha.', to='core.product', verbose_name='Produtos em Destaque')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Selecione a campanha para a qual este banner pertence. Deixe em branco para o banner ser um Padrão (aparecer quando nenhuma campanha estiver ativa).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.campaign', verbose_name='Campanha'),
        ),
    ]
