# Generated by Django 6.0.6 on 2026-06-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campaign_banner_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='📱 TAMANHO RECOMENDADO: 800 × 1000 px ou 1080 × 1350 px (formato vertical/retrato). Se preenchido, esta imagem será usada APENAS em telas de celulares, garantindo melhor legibilidade e visual. Se deixado em branco, a imagem principal (desktop) será espremida/ajustada no celular.', null=True, upload_to='banners/mobile/', verbose_name='Imagem Específica para Mobile (Opcional)'),
        ),
    ]
