# Generated by Django 6.0.6 on 2026-06-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_banner_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='featured_subtitle',
            field=models.TextField(blank=True, default='Seleção especial de materiais de construção com preços exclusivos na Matcon.', verbose_name='Subtítulo da Área de Destaque'),
        ),
    ]
