# Generated by Django 6.0.6 on 2026-06-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_campaign_featured_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Marca')),
                ('logo', models.ImageField(help_text='Recomendado: Imagens com fundo transparente (PNG) e altura/largura similares. Evite imagens com muito espaço em branco ao redor.', upload_to='marcas/', verbose_name='Logomarca')),
                ('url', models.URLField(blank=True, help_text='Se preenchido, a logo será clicável e levará a este link.', verbose_name='Link Opcional')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.IntegerField(default=0, help_text='Menores números aparecem primeiro.', verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
