# Generated by Django 6.0.6 on 2026-06-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], default='filial', max_length=10, verbose_name='Tipo')),
                ('title_eyebrow', models.CharField(blank=True, default='NOSSA LOCALIZAÇÃO', max_length=100, verbose_name='Texto de Apoio (Eyebrow)')),
                ('title_main', models.CharField(blank=True, default='ONDE NOS ENCONTRAR EM PORTO ALEGRE', max_length=150, verbose_name='Título Principal')),
                ('card_title', models.CharField(blank=True, default='VENHA TOMAR UM CAFÉ COM A GENTE!', max_length=100, verbose_name='Título do Card')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço (Rua, Número, Bairro)')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='RS', max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('business_hours', models.TextField(blank=True, help_text='Ex: Seg a Qui: 09h às 19:30h', verbose_name='Horários de Funcionamento')),
                ('mapa_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Incorporação do Google Maps (Iframe)')),
                ('rota_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Rota do Google Maps')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
